<?php
declare(strict_types=1);

/** @version 1.0.3 */

use Loki\Components\Factory\ViewModelFactory;
use Loki\Flatpickr\ViewModel\Options;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var Options $options */
$options = $viewModelFactory->create(Options::class);
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.directive('flatpickr', (el, {}) => {
            flatpickr(el, JSON.parse('<?= /* @noEscape */ $options->toJson($block) ?>'));
        });
    });
</script>
